# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=singogia
      - POSTGRES_DB=dispolitics
    networks:
      - dispolitics
networks:
  dispolitics:
    external: true